version: "3.8"

services:
    db:
        image: postgres:15-alpine
        container_name: basecamp-postgres-db
        environment:
            POSTGRES_DB: mybasecamp_db
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: ${MY_SECRET_DB_PASSWORD}
        ports:
            - "5432:5432"
        volumes:
            - postgres_data:/var/lib/postgresql/data
        networks:
            - basecamp-network

    app:
        build: .
        container_name: basecamp-spring-app
        ports:
            - "8080:8080"
        environment:
            - DB_URL=jdbc:postgresql://db:5432/mybasecamp_db
            - DB_USERNAME=postgres
            - DB_PASSWORD=${MY_SECRET_DB_PASSWORD}
        depends_on:
            - db
        networks:
            - basecamp-network

volumes:
    postgres_data:

networks:
    basecamp-network:
        driver: bridge
